### ISSUE TITLE
First Issue - How to start

### ISSUE THREAD

**Issue by WK-GiHu** [djvar94/gtk-simple-calculator-python3#2]
@djvar94 

Notify me with: @WK-GiHu

- [Stackoverflow - how-to-store-x-number-of-factors-from-user-input-gtk-textview-in-multi-factor](https://stackoverflow.com/questions/60510955)

### To **review** your code, update allways the files here after edit.

Start allways at the `[Issues]` page, i open for every single issue a **New Issue**. 

- [Gtk.TextBuffer.get_text](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TextBuffer.html#Gtk.TextBuffer.get_text)
- [Gtk.TextBuffer.get_start_iter](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TextBuffer.html#Gtk.TextBuffer.get_start_iter)
- [Gtk.TextBuffer.get_end_iter](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TextBuffer.html#Gtk.TextBuffer.get_end_iter)
- [eval](https://docs.python.org/3/library/functions.html#eval)

**Comment by djvar94** [comment]
@WK-GiHu I get the use of eval. However I still don't quite understand how do you implement the example on the Gtk.TextBuffer.get_text link you provided me. And can I write something like

`if buffer != (””):
             try:
                    eval(buffer)
             except ValueError:
                     invalidExpressionWarning = builder.get_object("invalidExpressionWarning")
                     invalidExpressionWarning.show()
else:
       pass`

Don't know how to include the indentation sorry. 
Wouldn't that be on the right track?
