### ISSUE TITLE
Upload your last edited source code

### ISSUE THREAD

**Issue by WK-GiHu** [djvar94/gtk-simple-calculator-python3#3]
@djvar94 

Upload, so i can review it

**Comment by djvar94** [comment]
@WK-GiHu Uhm, I uploaded the whole project folder to the development branch the files should be there, I don't think I can upload them in this page..sorry I'm still noob in GitHub..

**Comment by WK-GiHu** [comment]
@djvar94 

OK, got it you have it under the `development` branche.

**Comment by WK-GiHu** [comment]
@djvar94 

It's the initial version.
Update with your last edit.

**Comment by djvar94** [comment]
@WK-GiHu I haven't changed much really, I'm sort of confused on what to do. But I'll upload it nevertheless

**Comment by djvar94** [comment]
@WK-GiHu Sorry, the way you see it there, it's the way I have it too at the moment...
