### ISSUE TITLE
AttributeError: 'TextView' object has no attribute 'get_text

### ISSUE THREAD

**Issue by WK-GiHu** [djvar94/gtk-simple-calculator-python3#4]
@djvar94 

A `TextView` object is the GUI part, in general you don't have to use while you are using `Glade`.
`Glade` connects a `TextBuffer` object by default. To read and insert text you have use only this object.

**Comment by djvar94** [comment]
@WK-GiHu  Right ok, but it is right then when the `builder` gets the actual object from Glade into the code and then refer it with `Gtk.TextBuffer` right?

**Comment by WK-GiHu** [comment]
@djvar94 

>but it is right then when the builder gets the actual object from Glade into the code and then refer it with Gtk.TextBuffer right?

It's slightly different:
1. `Glade` is not part of any `Gtk` Python script.
2. `Gtk.Builder` read the `.glade` definition using `add_from_file(` and instantiates `Gtk` objects.
3. You get a reference to the instantiated objects using `.get_object(<object id>)`

---

In your case, `Glade` defines **only** a `Gtk.TextView` object.
At instantiation, a default `Gtk.TextBuffer` object get assigned to it.
You refer this default `Gtk.TextBuffer` using `.get_buffer()`

**Comment by WK-GiHu** [comment]
@djvar94 

Close this issue if the topic is solved.
