### ISSUE TITLE
gi.require_version("Gtk", "3.0")

### ISSUE THREAD

**Issue by WK-GiHu** [djvar94/gtk-simple-calculator-python3#5]
@djvar94 

This, `gi.require_version`
https://github.com/djvar94/gtk-simple-calculator-python3/blob/d993671c0df52ba409ae9b4a98141704eefbcee7/Simple%20Calculator/simple%20calculator.py#L6

have to be called before
https://github.com/djvar94/gtk-simple-calculator-python3/blob/d993671c0df52ba409ae9b4a98141704eefbcee7/Simple%20Calculator/simple%20calculator.py#L5

**Comment by djvar94** [comment]
@WK-GiHu Well, yes I know but that's the way vscode auto formats it with autopep8. It doesn't seem to give problems though, I mean the GUI works fine

**Comment by WK-GiHu** [comment]
@djvar94 

>It doesn't seem to give problems though, I mean the GUI works fine

You get a console warning message

**Comment by djvar94** [comment]
@WK-GiHu yes I knew that. I meant practically it doesn't affect the GUI. Programs work just fine even with the console warning. You get a warning even on popup warning messages like the invalid expression one. But they still work just fine.
