### ISSUE TITLE
how do you implement Gtk.TextBuffer.get_text

### ISSUE THREAD

**Issue by WK-GiHu** [djvar94/gtk-simple-calculator-python3#6]
@WK-GiHu I get the use of eval. However I still don't quite understand how do you implement the example on the Gtk.TextBuffer.get_text link you provided me. And can I write something like

```
if buffer != (””):
             try:
                    eval(buffer)
             except ValueError:
                     invalidExpressionWarning = builder.get_object("invalidExpressionWarning")
                     invalidExpressionWarning.show()
else:
       pass
```
Don't know how to include the indentation sorry. 
Wouldn't that be on the right track?

_Originally posted by @djvar94 in https://github.com/djvar94/gtk-simple-calculator-python3/issues/2#issuecomment-594473373_

**Comment by WK-GiHu** [comment]
@djvar94 

>Don't know how to include the indentation sorry.

Enclose withing three backticks '```'

---

> can I write something like

No, `buffer` is a reference to a `Gtk.TextBuffer` object and not the `text` itself.
Doing: `if buffer != (””):` you try to compare a `reference` with a `tuple(string)`.

Now you have:
https://github.com/djvar94/gtk-simple-calculator-python3/blob/d993671c0df52ba409ae9b4a98141704eefbcee7/Simple%20Calculator/simple%20calculator.py#L118

The definition is: `get_text(start, end, include_hidden_chars)`

- [x] You are missing one argument
- [x] You get `start` from [Gtk.TextBuffer.get_start_iter](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TextBuffer.html#Gtk.TextBuffer.get_start_iter)
- [x] You get `end` from [Gtk.TextBuffer.get_end_iter](http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TextBuffer.html#Gtk.TextBuffer.get_end_iter)

**Note**: These `iter` objects are only valid until the next changes to the `buffer` occures.

Update your source accordingly, so i can review.

**Comment by djvar94** [comment]
@WK-GiHu seems like I fixed the `start` and `end` parameters of .get_text method. the problem for me at the moment seems to be the `include_hidden_chars` bit. Python seems to see that as an undefined variable...:/

**Comment by djvar94** [comment]
@WK-GiHu I have just updated the code here on GitHub to reflect the change explained in my previous comment. That's what I have done so far and trying to understand how can I fix that undefined variable bit.

**Comment by WK-GiHu** [comment]
@djvar94 

>the problem for me at the moment seems to be the `include_hidden_chars` bit. Python seems to see that as an `undefined variable...:/`

https://github.com/djvar94/gtk-simple-calculator-python3/blob/bf3b5bb59a306e13fdaafaad06377e74e47bc293/Simple%20Calculator/simple%20calculator.py#L120

It's the name of the argument `include_hidden_chars` in `Gtk.TextBuffer.get_text(...`. 
It's simple a boolean to decide if you want also hidden chars from the `TextBuffer`.
You don't use hidden chars, therefore replace it with either `True` or `False`, e.g:
```
  .get_text(..., True) 
```

**Comment by djvar94** [comment]
@WK-GiHu Got it. Will do it tomorrow

**Comment by djvar94** [comment]
@WK-GiHu now I get this error on the console 
`include_hidden_chars = buffer.get_text(..., False)`
`TypeError: Gtk.TextBuffer.get_text() takes exactly 4 arguments (3 given)`

I have updated my code accordingly

**Comment by WK-GiHu** [comment]
@djvar94 

>`TypeError: Gtk.TextBuffer.get_text() takes exactly 4 arguments (3 given)`

When i write: `(..., False)`, the three dots are only placeholder to focus to the relevant argument, here `False`.

---

Replace the following **two** lines to **one** line:
https://github.com/djvar94/gtk-simple-calculator-python3/blob/0e2dbb6fb5831b623461ae7dc782b03e6802739c/Simple%20Calculator/simple%20calculator.py#L120-L121

```
expression = buffer.get_text(start, end, False) 
```

**Comment by djvar94** [comment]
@WK-GiHu  aaahh ok

**Comment by djvar94** [comment]
@Wk-GiHu Right ok, Thank you so much, I've managed to fix the issue of the warning message popup. the if/else loop now works as it should (I have committed the change to the code so you can see). So I could close this issue, and open now another one for evaluating the actual expression, if it's a valid expression then do it, if it isn't show the popup.
